// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSite(arg1) {
  return window['go']['sites']['SiteManager']['AddSite'](arg1);
}

export function DeleteSite(arg1) {
  return window['go']['sites']['SiteManager']['DeleteSite'](arg1);
}

export function GetSites() {
  return window['go']['sites']['SiteManager']['GetSites']();
}

export function OpenSiteFilesDir(arg1) {
  return window['go']['sites']['SiteManager']['OpenSiteFilesDir'](arg1);
}

export function PickDirectory() {
  return window['go']['sites']['SiteManager']['PickDirectory']();
}

export function SetContext(arg1) {
  return window['go']['sites']['SiteManager']['SetContext'](arg1);
}

export function StartSite(arg1) {
  return window['go']['sites']['SiteManager']['StartSite'](arg1);
}

export function StopSite(arg1) {
  return window['go']['sites']['SiteManager']['StopSite'](arg1);
}
