// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sites} from '../models';
import {context} from '../models';

export function AddSite(arg1:sites.Site):Promise<void>;

export function DeleteSite(arg1:string):Promise<void>;

export function GetSites():Promise<Array<sites.Site>>;

export function SetContext(arg1:context.Context):Promise<void>;
