// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {context} from '../models';

export function AddSite(arg1:types.Site):Promise<void>;

export function DeleteSite(arg1:string):Promise<void>;

export function GetSites():Promise<Array<types.Site>>;

export function SetContext(arg1:context.Context):Promise<void>;

export function StartSite(arg1:string):Promise<void>;

export function StopSite(arg1:string):Promise<void>;
