-- Down-migration: nothing to restore. The telemetry rows held opt-in
-- preferences and a hashed client ID generated by code that no longer
-- exists; rolling back this migration cannot conjure user intent that
-- was never persisted elsewhere. A no-op is the honest answer.
SELECT 1;
